### ISSUE TITLE
Implement SIP-1 

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#460]
Requirement: https://github.com/decentralized-identity/sidetree/issues/766 has been merged into Sidetree specification.

This PR is to keep track of PRs required to complete SIP-1:
- [x] Add writing of proof files to CAS (new) #459 
- [x] Retrieve proof files from CAS and validate them against new protocol parameters (new) #464 
- [x] Core and Provisional Index files, create struct for files to pass around #468
- [x] Retrieve signed data from proof files #470 
- [x] Validate batch files counts (across multiple files) #475
- [x] Use signed data from proof files for anchored operations #474 
- [x] Handle reveal value in core/provisional index files #480 
- [x] Additional batch files validations #485
- [x] Rename as per reference application #490 #498
- [x] Remove operations tag from core/provisional index if there are no relevant operations #495
- [x] Return an error if there are duplicate suffixes in core index file #493 
- [x] Add max proof and max delta size to protocol and validate batch file entries #512
- [x] Validate CAS URI #477
- [x] Add reveal value to update, recover, deactivate request #521
- [x] Support multiple hashing algorithms (an array) in protocol parameters
- [x] Enable reveal value validation
- [x] Remove proof size from parameters
...

@troyronda Out of scope for this release: Light weight node (not sure if we even have any value in implementing it - it is optional feature that enables a node to operate trustlessly)
...
